#if !canImport(ObjectiveC)
import XCTest

extension CachePersistenceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CachePersistenceTests = [
        ("testClearCache", testClearCache),
        ("testFetchAndPersist", testFetchAndPersist),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CachePersistenceTests.__allTests__CachePersistenceTests),
    ]
}
#endif
